version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: prote_db
      MYSQL_USER: prote
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - prote-net

  app:
    build:
      context: .
    container_name: spring-boot
    ports:
      - "8080:8080"
    environment:
      ACCESS_TIME: ${ACCESS_TIME}
      REFRESH_TIME: ${REFRESH_TIME}
      PREFIX: ${PREFIX}
      HEADER: ${HEADER}
      SECRET_KEY: ${SECRET_KEY}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MONGO_URL: ${MONGO_URL}
    depends_on:
      - mysql
    networks:
      - prote-net

networks:
  prote-net:
    driver: bridge

volumes:
  mysql-data: