spring:
  application:
    name: prote

  data:
    mongodb:
      uri: ${MONGO_URL}


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  access-time: ${ACCESS_TIME}
  refresh-time: ${REFRESH_TIME}
  prefix: ${PREFIX}
  header: ${HEADER}
  secret-key: ${SECRET_KEY}
