spring:
  application:
    name: prote

  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db-url}
    username: ${db-user}
    password: ${db-password}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  access-time: ${access-time}
  refresh-time: ${refresh-time}
  prefix: ${prefix}
  header: ${header}
  secret-key: ${secret-key}
