spring:
  application:
    name: prote

  data:
    mongodb:
      uri: ${MONGO_URL}
    redis:
      url: ${REDIS_URL}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  access-time: ${ACCESS_TIME}
  refresh-time: ${REFRESH_TIME}
  prefix: ${PREFIX}
  header: ${HEADER}
  secret-key: ${SECRET_KEY}

server:
  ssl:
    enabled: false
  forward-headers-strategy: native
  tomcat:
    redirect-context-root: false
    use-relative-redirects: true

springdoc:
  swagger-ui:
    url: https://lazy-shaylah-guhyunwoo-777b581b.koyeb.app/v3/api-docs